testing configure server

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -185,160 +185,160 @@ jobs:
           name: Configure server
           command: |
             ansible-playbook .circleci/ansible/configure-server.yml -i .circleci/ansible/inventory.txt
-  run-migrations: 
-    docker:
-      - image: cimg/node:13.8.0
-    steps:
-      - checkout
-      - run:
-          name: Run migrations
-          command: |
-            cd backend
-            npm install
-            npm run migrations > migrations_dump.txt 
+  # run-migrations: 
+  #   docker:
+  #     - image: cimg/node:13.8.0
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: Run migrations
+  #         command: |
+  #           cd backend
+  #           npm install
+  #           npm run migrations > migrations_dump.txt 
  
-      - run: 
-          name: Send Migration Results to kvdb.io
-          command: |
-            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
-            then
-              # If you are using kvdb.io, generate the bucket ID "Up68KQvVZCMC32AM4i2mJR" in your local terminal first
-              curl -d '1' https://kvdb.io/GAYvMRiwnAHenKsbLKCKot/migration_${CIRCLE_WORKFLOW_ID:0:7}  
-            fi
-      - revert-migrations
-      - destroy-environment
-  deploy-frontend:
-    docker:
-      - image: cimg/aws:2022.06.1
-    steps:
-      - checkout
-      - restore_cache:
-          keys: [frontend-build]
-      - run:
-          name: install tar and gzip
-          command: |
-           sudo apt install -y tar gzip
-      - run:
-          name: install ansible
-          command: |
-            python3 -m pip install --user ansible
-      - run:
-          name: Install Node.js 13.8.0
-          command: |
-            # Install Node.js LTS version as our base Node.js version
-            curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
-            sudo apt install -y nodejs
-            # Use n version manager to use Node.js v13.8.0
-            sudo npm install --global n
-            sudo n 13.8.0
+  #     - run: 
+  #         name: Send Migration Results to kvdb.io
+  #         command: |
+  #           if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+  #           then
+  #             If you are using kvdb.io, generate the bucket ID "Up68KQvVZCMC32AM4i2mJR" in your local terminal first
+  #             curl -d '1' https://kvdb.io/GAYvMRiwnAHenKsbLKCKot/migration_${CIRCLE_WORKFLOW_ID:0:7}  
+  #           fi
+  #     - revert-migrations
+  #     - destroy-environment
+  # deploy-frontend:
+  #   docker:
+  #     - image: cimg/aws:2022.06.1
+  #   steps:
+  #     - checkout
+  #     - restore_cache:
+  #         keys: [frontend-build]
+  #     - run:
+  #         name: install tar and gzip
+  #         command: |
+  #          sudo apt install -y tar gzip
+  #     - run:
+  #         name: install ansible
+  #         command: |
+  #           python3 -m pip install --user ansible
+  #     - run:
+  #         name: Install Node.js 13.8.0
+  #         command: |
+  #           Install Node.js LTS version as our base Node.js version
+  #           curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
+  #           sudo apt install -y nodejs
+  #           Use n version manager to use Node.js v13.8.0
+  #           sudo npm install --global n
+  #           sudo n 13.8.0
       
-      - run: 
-          name: backend url 
-          command: |
-            export BACKEND_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo "API_URL = ${API_URL}"
-            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
-            cat frontend/.env
-      - run:
-          name: deploy frontend 
-          command: |
-            cd frontend
-            npm install
-            npm run build
-            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
-            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
-      - destroy-environment
-      - revert-migrations
-  deploy-backend:
-    docker:
-      - image: cimg/aws:2022.06.1
-    steps:
-      - checkout
-      - restore_cache:
-          keys: [backend-build]
-      - add_ssh_keys:
-          fingerprints: ["05:e4:31:85:64:9b:7f:0f:b1:81:ea:61:30:e6:14:83"] # You can get this ID in the section where you registered the SSH Key
-      - attach_workspace:
-          at: ~/
-      - run:
-          name: install tar and gzip
-          command: |
-           sudo apt install -y tar gzip
-      - run:
-          name: install ansible
-          command: |
-            sudo apt update
-            sudo apt install python3-pip
-            python3 -m pip install --user ansible
-      - run:
-          name: Install Node.js 13.8.0
-          command: |
-            # Install Node.js LTS version as our base Node.js version
-            curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
-            sudo apt install -y nodejs
-            # Use n version manager to use Node.js v13.8.0
-            sudo npm install --global n
-            sudo n 13.8.0
-      - run:
-          name: env
-          command: |
-            export TYPEORM_MIGRATIONS_DIR=./migrations
-            export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
-            export TYPEORM_MIGRATIONS=./migrations/*.ts
-      - run:
-          name: deploy backend 
-          command: |
-            cd backend
-            npm i
-            npm run build
-            tar -czvf artifact.tar.gz dist/* package*
-            ls
-            cd .. 
-            cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
-            ls .circleci/ansible/roles/deploy/files
-            cd .circleci/ansible
-            echo "Contents  of the inventory.txt file is -------"
-            cat inventory.txt
-            ansible-playbook -i inventory.txt deploy-backend.yml
-      - destroy-environment
-      - revert-migrations
-  smoke-test:
-    docker:
-      - image: cimg/aws:2022.06.1
-    steps:
-      - checkout
-      - run:
-          name: install tar and gzip
-          command: |
-           sudo apt install -y tar gzip
+  #     - run: 
+  #         name: backend url 
+  #         command: |
+  #           export BACKEND_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
+  #           export API_URL="http://${BACKEND_IP}:3030"
+  #           echo "API_URL = ${API_URL}"
+  #           echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+  #           cat frontend/.env
+  #     - run:
+  #         name: deploy frontend 
+  #         command: |
+  #           cd frontend
+  #           npm install
+  #           npm run build
+  #           tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
+  #           aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+  #     - destroy-environment
+  #     - revert-migrations
+  # deploy-backend:
+  #   docker:
+  #     - image: cimg/aws:2022.06.1
+  #   steps:
+  #     - checkout
+  #     - restore_cache:
+  #         keys: [backend-build]
+  #     - add_ssh_keys:
+  #         fingerprints: ["05:e4:31:85:64:9b:7f:0f:b1:81:ea:61:30:e6:14:83"] # You can get this ID in the section where you registered the SSH Key
+  #     - attach_workspace:
+  #         at: ~/
+  #     - run:
+  #         name: install tar and gzip
+  #         command: |
+  #          sudo apt install -y tar gzip
+  #     - run:
+  #         name: install ansible
+  #         command: |
+  #           sudo apt update
+  #           sudo apt install python3-pip
+  #           python3 -m pip install --user ansible
+  #     - run:
+  #         name: Install Node.js 13.8.0
+  #         command: |
+  #           Install Node.js LTS version as our base Node.js version
+  #           curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
+  #           sudo apt install -y nodejs
+  #           Use n version manager to use Node.js v13.8.0
+  #           sudo npm install --global n
+  #           sudo n 13.8.0
+  #     - run:
+  #         name: env
+  #         command: |
+  #           export TYPEORM_MIGRATIONS_DIR=./migrations
+  #           export TYPEORM_ENTITIES=./modules/domain/**/*.entity{.ts,.js}
+  #           export TYPEORM_MIGRATIONS=./migrations/*.ts
+  #     - run:
+  #         name: deploy backend 
+  #         command: |
+  #           cd backend
+  #           npm i
+  #           npm run build
+  #           tar -czvf artifact.tar.gz dist/* package*
+  #           ls
+  #           cd .. 
+  #           cp backend/artifact.tar.gz .circleci/ansible/roles/deploy/files
+  #           ls .circleci/ansible/roles/deploy/files
+  #           cd .circleci/ansible
+  #           echo "Contents  of the inventory.txt file is -------"
+  #           cat inventory.txt
+  #           ansible-playbook -i inventory.txt deploy-backend.yml
+  #     - destroy-environment
+  #     - revert-migrations
+  # smoke-test:
+  #   docker:
+  #     - image: cimg/aws:2022.06.1
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: install tar and gzip
+  #         command: |
+  #          sudo apt install -y tar gzip
       
-      - run:
-          name: back end smoke test
-          command: |
-            export BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --output text)
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo "${API_URL}"
-            if curl "${API_URL}/api/status" | grep "ok"
-            then
-              exit 0
-            else
-              exit 1
-            fi
+  #     - run:
+  #         name: back end smoke test
+  #         command: |
+  #           export BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --output text)
+  #           export API_URL="http://${BACKEND_IP}:3030"
+  #           echo "${API_URL}"
+  #           if curl "${API_URL}/api/status" | grep "ok"
+  #           then
+  #             exit 0
+  #           else
+  #             exit 1
+  #           fi
             
-      - run:
-          name: Frontend smoke test.
-          command: |
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
-            echo ${URL} 
-            if curl -s ${URL} | grep "Welcome"
-            then
-              exit 0
-            else
-              exit 1
-            fi
-      - destroy-environment 
-      - revert-migrations  
+  #     - run:
+  #         name: Frontend smoke test.
+  #         command: |
+  #           URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+  #           echo ${URL} 
+  #           if curl -s ${URL} | grep "Welcome"
+  #           then
+  #             exit 0
+  #           else
+  #             exit 1
+  #           fi
+  #     - destroy-environment 
+  #     - revert-migrations  
 #   cloudfront-update:
 #     docker:
 #       # Docker image here that supports AWS CLI
@@ -391,15 +391,15 @@ workflows:
           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
-      - run-migrations:
-          requires: [configure-infrastructure]
-      - deploy-frontend:
-          requires: [run-migrations]
-      - deploy-backend:
-          requires: [run-migrations]
-      - smoke-test:
-          requires: [deploy-backend, deploy-frontend]
-      # - cloudfront-update:
-      #     requires: [smoke-test]
-      # - cleanup:
-      #     requires: [cloudfront-update]
+      # - run-migrations:
+      #     requires: [configure-infrastructure]
+      # - deploy-frontend:
+      #     requires: [run-migrations]
+      # - deploy-backend:
+      #     requires: [run-migrations]
+      # - smoke-test:
+      #     requires: [deploy-backend, deploy-frontend]
+      # # - cloudfront-update:
+      # #     requires: [smoke-test]
+      # # - cleanup:
+      # #     requires: [cloudfront-update]
